backend:
  name: github
  repo: guayo/dulcevida
  branch: master

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "source/localizable/test"
    sort: "weight:asc"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "content"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "subtitle", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
