backend:
  name: github
  repo: guayo/dulcevida
  branch: master

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "/la-dulce-vida/" # Used in routes, e.g. /admin/collections/blog
    label: "La dulce vida" # Used in the UI
    folder: "source/localizable/la-dulce-vida" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{urlname}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "content"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "dubtitle", widget: "string"}
      - {label: "Wight", name: "weight", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "number"}
