backend:
  name: github
  repo: guayom/dulcevida
  branch: master

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "beach-club"
    label: "Beach club articles"
    folder: "source/localizable/beach-club"
    sort: "weight:asc"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "content"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "subtitle", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
