backend:
  name: github
  repo: guayo/dulcevida
  branch: master

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "localizable"
    label: "Localizable"
    folder: "source/localizable"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "content"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "dubtitle", widget: "string"}
      - {label: "Wight", name: "weight", widget: "number"}
